// These settings override both User and Default settings for the Dockerfile syntax
{
  "tab_size": 2,
  "tabs_medium": true,
  "translate_tabs_to_spaces": true,
  "trim_trailing_white_space_on_save": true

}
