#!/bin/bash

if [ -z ${AWS_SESSION_TOKEN+x} ]; then
  echo "AWS_SESSION_TOKEN not set"
  exit 1
fi

token=$(kubectl-token)

open "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login"

kubectl proxy
