#!/bin/bash

DOCKER_ADDS="-q -f dangling=true "
if [ -z "$1" ]
  then
    DOCKER_CMD=docker
  else
    echo "run remotely: "
    DOCKER_CERT_PATH=$HOME/.config/ssl/docker-eccenca
    DOCKER_HOST=https://$1.eccenca.com:2375
    DOCKER_TLS_VERIFY=true
    DOCKER_CMD="docker --tlsverify --tlscacert=$DOCKER_CERT_PATH/ca.pem --tlscert=$DOCKER_CERT_PATH/client-cert.pem --tlskey=$DOCKER_CERT_PATH/client-key.pem -H=$1.eccenca.com:2375"
fi

if [ ! -z "$2" ]
  then
    DOCKER_ADDS=" | grep $2  | tr -s ' ' | cut -f3 -d ' '"
fi

echo $DOCKER_ADDS
$DOCKER_CMD images $DOCKER_ADDS| parallel $DOCKER_CMD rmi {}