#!/bin/bash

if [ -z "$1" ]
  then
    DOCKER_CMD=docker
  else
    echo "run remotely: "
    DOCKER_CERT_PATH=$HOME/.config/ssl/docker-eccenca
    DOCKER_HOST=https://$1.eccenca.com:2375
    DOCKER_TLS_VERIFY=true
    DOCKER_CMD="docker --tlsverify --tlscacert=$DOCKER_CERT_PATH/ca.pem --tlscert=$DOCKER_CERT_PATH/client-cert.pem --tlskey=$DOCKER_CERT_PATH/client-key.pem -H=$1.eccenca.com:2375"
fi
 
$DOCKER_CMD rm $($DOCKER_CMD ps -q -a)