source /Users/hknochenhauer/.bootstrap_rc

##### ~/.zprofile #####
eval "$(pyenv init --path)"

##### ~/.zshrc #####
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

export LANG="en-US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8

##### ~/.zprofile #####
eval "$(pyenv init --path)"

#load fasd
eval "$(fasd --init auto)"
export GPG_TTY=$(tty)
# Load all files from .dotfiles/zsh/ directory
if [ -d $HOME/.dotfiles/zsh ]; then
  for file in $HOME/.dotfiles/zsh/*.zsh; do
    source $file
  done
fi

#customization
source ${HOME}/.dotfiles/sfdc-cc/zshrc_extension
export MAIL_ADDRESSES="${CUSTOM_MAIL_ADDRESS} hknochi@users.noreply.github.com hknochi@gmail.com"
export USER="Henri Knochenhauer"

# add your name to your .gitconfig
git config --global user.name "${USER}"

export PATH="/usr/local/bin:$PATH"


__git_files () { 
    _wanted files expl 'local files' _files 
}

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/mc mc
